print("'Introduction to programming':Task 1")
print(" Maksym Slobodchykov, IKM-221a")
print(44*"Vladislav Ovsianikov, ","Vladislav Ovsianikov.")
print("Show rusult:")
print(7.8 -((1+(2.1/3))/(78+21.3)))